import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const page = await readFile(new URL("../src/app/page.tsx", import.meta.url), "utf8");
const shell = await readFile(new URL("../src/app/control-center-shell.tsx", import.meta.url), "utf8");
const overview = await readFile(new URL("../src/app/overview-panels.tsx", import.meta.url), "utf8");
const layout = await readFile(new URL("../src/app/layout.tsx", import.meta.url), "utf8");
const controlState = await readFile(new URL("../src/app/control-state-panel.tsx", import.meta.url), "utf8");
const permissionsPanel = await readFile(new URL("../src/app/permissions-panel.tsx", import.meta.url), "utf8");
const auditPanel = await readFile(new URL("../src/app/audit-panel.tsx", import.meta.url), "utf8");
const login = await readFile(new URL("../src/app/login/page.tsx", import.meta.url), "utf8");
const sessionPanel = await readFile(new URL("../src/app/session-panel.tsx", import.meta.url), "utf8");
const styles = await readFile(new URL("../src/app/globals.css", import.meta.url), "utf8");

assert.match(page, /ControlCenterShell/);
assert.match(shell, /control-center-shell/);
assert.match(shell, /control-grid/);
assert.match(shell, /hero-panel/);
assert.match(shell, /NOVO Control Center/);
assert.match(shell, /Current phase/);
assert.match(shell, /E2 frontend control center/);
assert.match(shell, /Sign in/);
assert.match(shell, /06037dd15f67cd8a21a4d627c5854160.mp4/);
assert.match(shell, /SessionPanel/);
assert.match(shell, /BackendHealthCard/);
assert.match(overview, /overview-grid/);
assert.match(overview, /Audit snapshot/);
assert.match(overview, /System status/);
assert.match(controlState, /Control state/);
assert.match(permissionsPanel, /Permissions/);
assert.match(auditPanel, /Audit/);
assert.match(layout, /metadata/);
assert.match(login, /Sign in to the Control Center/);
assert.match(login, /HttpOnly cookies/);
assert.match(login, /credentials: "include"/);
assert.match(sessionPanel, /auth\/me/);
assert.match(sessionPanel, /credentials: "include"/);
assert.match(sessionPanel, /novo_csrf_token/);
assert.match(sessionPanel, /Sign out/);
assert.match(styles, /\.control-center-shell/);
assert.match(styles, /\.control-grid/);
assert.match(styles, /\.hero-panel/);
assert.match(styles, /\.overview-grid/);
assert.match(styles, /\.overview-card/);
assert.match(styles, /\.governance-grid/);
assert.match(styles, /\.governance-card/);

console.log("NOVO frontend smoke check passed");